[workspace]
members = [
    "jmespath",
    "jmespath-cli",
]
resolver = "2"

[workspace.package]
edition = "2024"

[workspace.dependencies]
serde = { version = "1", features = ["rc"] }
serde_json = "1"
